os: osx
cache:
  directories:
  - $HOME/.macports-ci-ccache

# install:
#   # set columns in terminal, required for curl to work correctly:
#   - export COLUMNS=80
#   - wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
#   - chmod +x ./macports-ci
#   - ./macports-ci install
#   - export PATH=/opt/local/bin:$PATH
#   - ./macports-ci ccache
#   - ./macports-ci localports "$PWD"

script:
# - travis_wait 30 sudo port install 
  - brew install autoconf automake libtool boost openssl pkg-config protobuf qt@5.5 qrencode
  - brew link qt@5.5 --force
  - qmake
  - make
  # - ./macports-ci ccache --save